"""Add prescriptions table

Revision ID: d2d4f83b623b
Revises: e957d7ffda4e
Create Date: 2025-09-24 19:54:21.453525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2d4f83b623b'
down_revision: Union[str, Sequence[str], None] = 'e957d7ffda4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescriptions_id'))

    op.drop_table('prescriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prescriptions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('medication', sa.VARCHAR(), nullable=False),
    sa.Column('dosage', sa.VARCHAR(), nullable=False),
    sa.Column('issued_date', sa.DATETIME(), nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescriptions_id'), ['id'], unique=False)

    # ### end Alembic commands ###
