# Disclaimers for all AI/chatbot responses

AI_DISCLAIMER = (
    "This response is generated by an AI assistant and is not a substitute for professional medical advice. "
    "If this is an emergency, contact your local emergency services."
)

def get_disclaimer():
    return AI_DISCLAIMER